// Copyright (C) 2009, 2010 by Florent Lamiraux, Thomas Moulard, JRL.
//
// This file is part of the hpp-corbaserver.
//
// This software is provided "as is" without warranty of any kind,
// either expressed or implied, including but not limited to the
// implied warranties of fitness for a particular purpose.
//
// See the COPYING file for more information.

#ifndef HPP_CORBASERVER_HRP2_SERVER_IDL
# define HPP_CORBASERVER_HRP2_SERVER_IDL

module hpp
{
  /**
   * \brief Interface to communicate with hrp2-genom component
   */
  interface Hrp2 {
    /// \brief Initialization of component
    /// \param initp whether the stabilizer is used
    short Init(in boolean initp);
  };
};

#endif //! HPP_CORBASERVER_HRP2_SERVER_IDL
